# Generated by Django 4.0.5 on 2022-07-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0017_alter_mechanic2_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic2',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/MechanicProfilePic2/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='problem_description',
            field=models.CharField(choices=[('water leak', 'water leak'), ('water shortage', 'water shortage'), ('water change related', 'water change related'), ('sewerage complaints', 'sewerage complaints')], max_length=50),
        ),
    ]
