# Generated by Django 4.0.5 on 2022-07-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0018_alter_mechanic2_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='work_category',
            field=models.CharField(choices=[('Engineer', 'Engineer'), ('Other', 'Other')], max_length=50),
        ),
    ]
