# Generated by Django 4.0.5 on 2022-07-09 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0019_alter_mechanic_work_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='mechanic2',
            name='profile_pic',
        ),
    ]
